version: '3.8'

services:
  loiter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loiter-app
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://loiter-redis:6379
      - AUTH_SECRET=8e6b9c944d188094f9958784d12c5b74
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=https://loiter.net
    depends_on:
      redis:
        condition: service_started
    networks:
      - srv_default

  redis:
    image: redis:7-alpine
    container_name: loiter-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - loiter_redis_data:/data
    networks:
      - srv_default

  nitter:
    image: zedeus/nitter:latest
    container_name: loiter-nitter
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nitter/nitter.conf:/src/nitter.conf:ro
      - ./nitter/sessions.jsonl:/src/sessions.jsonl:ro
    depends_on:
      - redis
    networks:
      - srv_default

  rss-bridge:
    image: rssbridge/rss-bridge:latest
    container_name: loiter-rss-bridge
    restart: always
    ports:
      - "3002:80"
    networks:
      - srv_default

networks:
  srv_default:
    external: true

volumes:
  loiter_redis_data:

