[Server]
hostname = "localhost:8080"
title = "Loiter Private Nitter"
address = "0.0.0.0"
port = 8080
https = false
httpMaxConnections = 100
staticDir = "./public"

[Cache]
listMinutes = 240
rssMinutes = 10
redisHost = "loiter-redis"
redisPort = 6379
redisPassword = ""
redisConnections = 20
redisMaxConnections = 30

[Config]
hmacKey = "loitersecretkey"
base64Media = false
enableRSS = true
enableRSSUserTweets = true
enableRSSUserReplies = true
enableRSSUserMedia = true
enableRSSSearch = true
enableRSSList = true
enableDebug = false
maxConcurrentReqs = 2
maxRetries = 1
retryDelayMs = 150

[Preferences]
theme = "Nitter"
replaceTwitter = "twitter.com"
proxyVideos = true
hlsPlayback = false
infiniteScroll = false
